// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_plagiarism.proto

/*
Package plagiari_sm_grpc_plagiarism is a generated protocol buffer package.

Package name (~DNS)

It is generated from these files:
	grpc_plagiarism.proto

It has these top-level messages:
	RequestDocument
	Notification
*/
package plagiari_sm_grpc_plagiarism

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RequestDocument from Elasticsearch
type RequestDocument struct {
	// article id
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *RequestDocument) Reset()                    { *m = RequestDocument{} }
func (m *RequestDocument) String() string            { return proto.CompactTextString(m) }
func (*RequestDocument) ProtoMessage()               {}
func (*RequestDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestDocument) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Notification
type Notification struct {
	// success, error
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	// 200, 500
	Code int32 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	// message
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	// label
	Label string `protobuf:"bytes,4,opt,name=label" json:"label,omitempty"`
	// article id
	Id int64 `protobuf:"varint,5,opt,name=id" json:"id,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Notification) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Notification) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Notification) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Notification) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Notification) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestDocument)(nil), "plagiari.sm.grpc.plagiarism.RequestDocument")
	proto.RegisterType((*Notification)(nil), "plagiari.sm.grpc.plagiarism.Notification")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Plagiarism service

type PlagiarismClient interface {
	// Endpoint Detect
	Detect(ctx context.Context, in *RequestDocument, opts ...grpc.CallOption) (*Notification, error)
}

type plagiarismClient struct {
	cc *grpc.ClientConn
}

func NewPlagiarismClient(cc *grpc.ClientConn) PlagiarismClient {
	return &plagiarismClient{cc}
}

func (c *plagiarismClient) Detect(ctx context.Context, in *RequestDocument, opts ...grpc.CallOption) (*Notification, error) {
	out := new(Notification)
	err := grpc.Invoke(ctx, "/plagiari.sm.grpc.plagiarism.Plagiarism/Detect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Plagiarism service

type PlagiarismServer interface {
	// Endpoint Detect
	Detect(context.Context, *RequestDocument) (*Notification, error)
}

func RegisterPlagiarismServer(s *grpc.Server, srv PlagiarismServer) {
	s.RegisterService(&_Plagiarism_serviceDesc, srv)
}

func _Plagiarism_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlagiarismServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plagiari.sm.grpc.plagiarism.Plagiarism/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlagiarismServer).Detect(ctx, req.(*RequestDocument))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plagiarism_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plagiari.sm.grpc.plagiarism.Plagiarism",
	HandlerType: (*PlagiarismServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _Plagiarism_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_plagiarism.proto",
}

func init() { proto.RegisterFile("grpc_plagiarism.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x6d, 0xdf, 0x6b, 0xc5, 0x41, 0x14, 0x06, 0x95, 0xa0, 0x9b, 0xda, 0x55, 0x05, 0xc9,
	0x42, 0x7f, 0xa1, 0x6b, 0x91, 0xfc, 0x80, 0xa4, 0xe9, 0x58, 0x02, 0x4d, 0xd3, 0x36, 0xd3, 0x8d,
	0x5f, 0x2f, 0xc6, 0x56, 0xc5, 0x45, 0x77, 0xb9, 0x97, 0x03, 0x37, 0x67, 0xe0, 0xba, 0x9b, 0x47,
	0xf3, 0x36, 0xf6, 0xba, 0xb3, 0x7a, 0xb6, 0xc1, 0xc9, 0x71, 0xf6, 0xec, 0xf1, 0x6e, 0x6b, 0x64,
	0x70, 0xf2, 0x0b, 0x91, 0xbf, 0x48, 0x79, 0x0f, 0x97, 0x8a, 0xa6, 0x85, 0x02, 0xd7, 0xde, 0x2c,
	0x8e, 0x06, 0xc6, 0x0b, 0x48, 0x6d, 0x2b, 0x92, 0x22, 0xa9, 0x0e, 0x2a, 0xb5, 0x6d, 0xf9, 0x01,
	0xe7, 0x2f, 0x9e, 0xed, 0xbb, 0x35, 0x9a, 0xad, 0x1f, 0xf0, 0x06, 0xf2, 0xc0, 0x9a, 0x97, 0x10,
	0x99, 0x33, 0xb5, 0x26, 0x44, 0x38, 0x1a, 0xdf, 0x92, 0x48, 0x8b, 0xa4, 0xca, 0x54, 0x7c, 0xa3,
	0x80, 0x53, 0x47, 0x21, 0xe8, 0x8e, 0xc4, 0x21, 0xc2, 0x5b, 0xc4, 0x2b, 0xc8, 0x7a, 0xdd, 0x50,
	0x2f, 0x8e, 0xb1, 0xff, 0x0e, 0xeb, 0x76, 0xb6, 0x6d, 0x3f, 0x4d, 0x00, 0xaf, 0x3f, 0x9f, 0x45,
	0x03, 0x79, 0x4d, 0x4c, 0x86, 0xf1, 0x51, 0xee, 0x48, 0xc9, 0x7f, 0x46, 0xb7, 0x0f, 0xbb, 0xf4,
	0x5f, 0xb9, 0xf2, 0xa4, 0xc9, 0xe3, 0xd5, 0x9e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x45,
	0x7e, 0xcd, 0x4e, 0x01, 0x00, 0x00,
}
