// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: plagiarism/grpc_plagiarism.proto

// Package name (~DNS)

package plagiarism

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestDocument from Elasticsearch
type RequestDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// article id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestDocument) Reset() {
	*x = RequestDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDocument) ProtoMessage() {}

func (x *RequestDocument) ProtoReflect() protoreflect.Message {
	mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDocument.ProtoReflect.Descriptor instead.
func (*RequestDocument) Descriptor() ([]byte, []int) {
	return file_plagiarism_grpc_plagiarism_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Notification
type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// success, error
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 200, 500
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// label
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// article id
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_plagiarism_grpc_plagiarism_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RequestOneToManyDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToCompare []string `protobuf:"bytes,2,rep,name=toCompare,proto3" json:"toCompare,omitempty"`
}

func (x *RequestOneToManyDocument) Reset() {
	*x = RequestOneToManyDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestOneToManyDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOneToManyDocument) ProtoMessage() {}

func (x *RequestOneToManyDocument) ProtoReflect() protoreflect.Message {
	mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOneToManyDocument.ProtoReflect.Descriptor instead.
func (*RequestOneToManyDocument) Descriptor() ([]byte, []int) {
	return file_plagiarism_grpc_plagiarism_proto_rawDescGZIP(), []int{2}
}

func (x *RequestOneToManyDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestOneToManyDocument) GetToCompare() []string {
	if x != nil {
		return x.ToCompare
	}
	return nil
}

type OneToManyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Result `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
}

func (x *OneToManyResponse) Reset() {
	*x = OneToManyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneToManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneToManyResponse) ProtoMessage() {}

func (x *OneToManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneToManyResponse.ProtoReflect.Descriptor instead.
func (*OneToManyResponse) Descriptor() ([]byte, []int) {
	return file_plagiarism_grpc_plagiarism_proto_rawDescGZIP(), []int{3}
}

func (x *OneToManyResponse) GetResult() []*Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Code   int32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Source string  `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Target string  `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Score  float64 `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_plagiarism_grpc_plagiarism_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_plagiarism_grpc_plagiarism_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Result) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Result) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Result) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_plagiarism_grpc_plagiarism_proto protoreflect.FileDescriptor

var file_plagiarism_grpc_plagiarism_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x22, 0x21,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x7a, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a,
	0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x54, 0x6f, 0x4d, 0x61, 0x6e,
	0x79, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x4f, 0x6e, 0x65, 0x54, 0x6f,
	0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x32, 0xa3, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72,
	0x69, 0x73, 0x6d, 0x12, 0x41, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x2e,
	0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x6c, 0x61,
	0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x09, 0x4f, 0x6e, 0x65, 0x54, 0x6f, 0x4d,
	0x61, 0x6e, 0x79, 0x12, 0x24, 0x2e, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x54, 0x6f, 0x4d, 0x61, 0x6e,
	0x79, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6c, 0x61, 0x67,
	0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x4f, 0x6e, 0x65, 0x54, 0x6f, 0x4d, 0x61, 0x6e, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x9a, 0x01, 0x0a, 0x0e, 0x63,
	0x6f, 0x6d, 0x2e, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x42, 0x13, 0x47,
	0x72, 0x70, 0x63, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x2d, 0x73, 0x6d, 0x2f, 0x73, 0x76, 0x63,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73,
	0x6d, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61,
	0x72, 0x69, 0x73, 0x6d, 0xca, 0x02, 0x0a, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73,
	0x6d, 0xe2, 0x02, 0x16, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x50, 0x6c, 0x61,
	0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plagiarism_grpc_plagiarism_proto_rawDescOnce sync.Once
	file_plagiarism_grpc_plagiarism_proto_rawDescData = file_plagiarism_grpc_plagiarism_proto_rawDesc
)

func file_plagiarism_grpc_plagiarism_proto_rawDescGZIP() []byte {
	file_plagiarism_grpc_plagiarism_proto_rawDescOnce.Do(func() {
		file_plagiarism_grpc_plagiarism_proto_rawDescData = protoimpl.X.CompressGZIP(file_plagiarism_grpc_plagiarism_proto_rawDescData)
	})
	return file_plagiarism_grpc_plagiarism_proto_rawDescData
}

var file_plagiarism_grpc_plagiarism_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plagiarism_grpc_plagiarism_proto_goTypes = []interface{}{
	(*RequestDocument)(nil),          // 0: plagiarism.RequestDocument
	(*Notification)(nil),             // 1: plagiarism.Notification
	(*RequestOneToManyDocument)(nil), // 2: plagiarism.RequestOneToManyDocument
	(*OneToManyResponse)(nil),        // 3: plagiarism.OneToManyResponse
	(*Result)(nil),                   // 4: plagiarism.Result
}
var file_plagiarism_grpc_plagiarism_proto_depIdxs = []int32{
	4, // 0: plagiarism.OneToManyResponse.Result:type_name -> plagiarism.Result
	0, // 1: plagiarism.Plagiarism.Detect:input_type -> plagiarism.RequestDocument
	2, // 2: plagiarism.Plagiarism.OneToMany:input_type -> plagiarism.RequestOneToManyDocument
	1, // 3: plagiarism.Plagiarism.Detect:output_type -> plagiarism.Notification
	3, // 4: plagiarism.Plagiarism.OneToMany:output_type -> plagiarism.OneToManyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plagiarism_grpc_plagiarism_proto_init() }
func file_plagiarism_grpc_plagiarism_proto_init() {
	if File_plagiarism_grpc_plagiarism_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plagiarism_grpc_plagiarism_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plagiarism_grpc_plagiarism_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plagiarism_grpc_plagiarism_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestOneToManyDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plagiarism_grpc_plagiarism_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneToManyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plagiarism_grpc_plagiarism_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plagiarism_grpc_plagiarism_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plagiarism_grpc_plagiarism_proto_goTypes,
		DependencyIndexes: file_plagiarism_grpc_plagiarism_proto_depIdxs,
		MessageInfos:      file_plagiarism_grpc_plagiarism_proto_msgTypes,
	}.Build()
	File_plagiarism_grpc_plagiarism_proto = out.File
	file_plagiarism_grpc_plagiarism_proto_rawDesc = nil
	file_plagiarism_grpc_plagiarism_proto_goTypes = nil
	file_plagiarism_grpc_plagiarism_proto_depIdxs = nil
}
