// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enrich/grpc_enrich.proto

// Package name (~DNS)

package mediawatch_io_enrich

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d518691d58a63d1, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Request) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type NLP struct {
	Stopwords            []string `protobuf:"bytes,1,rep,name=stopwords,proto3" json:"stopwords,omitempty"`
	Keywords             []string `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Topics               []string `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NLP) Reset()         { *m = NLP{} }
func (m *NLP) String() string { return proto.CompactTextString(m) }
func (*NLP) ProtoMessage()    {}
func (*NLP) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d518691d58a63d1, []int{1}
}

func (m *NLP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NLP.Unmarshal(m, b)
}
func (m *NLP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NLP.Marshal(b, m, deterministic)
}
func (m *NLP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NLP.Merge(m, src)
}
func (m *NLP) XXX_Size() int {
	return xxx_messageInfo_NLP.Size(m)
}
func (m *NLP) XXX_DiscardUnknown() {
	xxx_messageInfo_NLP.DiscardUnknown(m)
}

var xxx_messageInfo_NLP proto.InternalMessageInfo

func (m *NLP) GetStopwords() []string {
	if m != nil {
		return m.Stopwords
	}
	return nil
}

func (m *NLP) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *NLP) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type Data struct {
	Nlp                  *NLP     `protobuf:"bytes,1,opt,name=nlp,proto3" json:"nlp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d518691d58a63d1, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetNlp() *NLP {
	if m != nil {
		return m.Nlp
	}
	return nil
}

type Response struct {
	// success, error
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 200, 500
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// data Object {}
	Data                 *Data    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d518691d58a63d1, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "mediawatch.io.enrich.Request")
	proto.RegisterType((*NLP)(nil), "mediawatch.io.enrich.NLP")
	proto.RegisterType((*Data)(nil), "mediawatch.io.enrich.Data")
	proto.RegisterType((*Response)(nil), "mediawatch.io.enrich.Response")
}

func init() { proto.RegisterFile("enrich/grpc_enrich.proto", fileDescriptor_5d518691d58a63d1) }

var fileDescriptor_5d518691d58a63d1 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xfe, 0x75, 0xed, 0xaf, 0x5b, 0x5f, 0x6f, 0x41, 0x24, 0x16, 0x95, 0xd1, 0xd3, 0x40, 0x88,
	0xb8, 0x7d, 0x05, 0xf5, 0x34, 0x46, 0xc9, 0xc5, 0xa3, 0x64, 0x6d, 0xe8, 0x8a, 0x5b, 0x13, 0xfb,
	0x66, 0x8c, 0xdd, 0xfc, 0xe8, 0x92, 0x37, 0x55, 0x2f, 0xf5, 0xf6, 0xfc, 0x6b, 0x79, 0x9e, 0x37,
	0xc0, 0x75, 0xd7, 0xb7, 0xd5, 0xee, 0xa1, 0xe9, 0x6d, 0xf5, 0x16, 0xb0, 0xb0, 0xbd, 0x71, 0x86,
	0x5d, 0x1e, 0x74, 0xdd, 0xaa, 0x93, 0x72, 0xd5, 0x4e, 0xb4, 0x46, 0x04, 0xaf, 0x78, 0x84, 0xa9,
	0xd4, 0x1f, 0x47, 0x8d, 0x8e, 0x31, 0x48, 0xb6, 0xa6, 0x3e, 0xf3, 0x68, 0x1e, 0x2d, 0x32, 0x49,
	0xd8, 0x6b, 0x7b, 0xd5, 0x35, 0x7c, 0x12, 0x34, 0x8f, 0x8b, 0x57, 0x88, 0x37, 0xeb, 0x92, 0xdd,
	0x40, 0x86, 0xce, 0xd8, 0x93, 0xe9, 0x6b, 0xe4, 0xd1, 0x3c, 0x5e, 0x64, 0xf2, 0x57, 0x60, 0x39,
	0xcc, 0xde, 0xf5, 0x39, 0x98, 0x13, 0x32, 0x7f, 0x38, 0xbb, 0x82, 0xd4, 0x19, 0xdb, 0x56, 0xc8,
	0x63, 0x72, 0x06, 0x56, 0xac, 0x20, 0x79, 0x52, 0x4e, 0xb1, 0x7b, 0x88, 0xbb, 0xbd, 0xa5, 0x1e,
	0x17, 0xcb, 0x6b, 0x31, 0xd6, 0x5b, 0x6c, 0xd6, 0xa5, 0xf4, 0xa9, 0xe2, 0x33, 0x82, 0x99, 0xd4,
	0x68, 0x4d, 0x87, 0xda, 0xff, 0x19, 0x9d, 0x72, 0x47, 0x1c, 0x46, 0x0c, 0xcc, 0xcf, 0xa8, 0x4c,
	0xad, 0x69, 0xc6, 0x7f, 0x49, 0x98, 0x71, 0x98, 0x1e, 0x34, 0xa2, 0x6a, 0x34, 0x8f, 0x29, 0xfc,
	0x4d, 0x99, 0x80, 0xa4, 0x56, 0x4e, 0xf1, 0x84, 0x0a, 0xe4, 0xe3, 0x05, 0x7c, 0x53, 0x49, 0xb9,
	0x65, 0x09, 0xe9, 0x33, 0x89, 0xec, 0x25, 0x9c, 0xe6, 0x76, 0xfc, 0x93, 0xe1, 0xd0, 0xf9, 0xdd,
	0x5f, 0x76, 0x58, 0x51, 0xfc, 0xdb, 0xa6, 0xf4, 0x64, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xeb, 0x3a, 0xe4, 0x26, 0xce, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EnrichClient is the client API for Enrich service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnrichClient interface {
	NLP(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type enrichClient struct {
	cc *grpc.ClientConn
}

func NewEnrichClient(cc *grpc.ClientConn) EnrichClient {
	return &enrichClient{cc}
}

func (c *enrichClient) NLP(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mediawatch.io.enrich.Enrich/NLP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrichServer is the server API for Enrich service.
type EnrichServer interface {
	NLP(context.Context, *Request) (*Response, error)
}

// UnimplementedEnrichServer can be embedded to have forward compatible implementations.
type UnimplementedEnrichServer struct {
}

func (*UnimplementedEnrichServer) NLP(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NLP not implemented")
}

func RegisterEnrichServer(s *grpc.Server, srv EnrichServer) {
	s.RegisterService(&_Enrich_serviceDesc, srv)
}

func _Enrich_NLP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichServer).NLP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mediawatch.io.enrich.Enrich/NLP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichServer).NLP(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Enrich_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mediawatch.io.enrich.Enrich",
	HandlerType: (*EnrichServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NLP",
			Handler:    _Enrich_NLP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enrich/grpc_enrich.proto",
}
